cloudProvider:
  storageClass: default-rwo

ocs:
  jobTerminationGracePeriod: 300
  namespace: openshift-storage
  mon:
    requests:
      cpu: 1
      memory: 2Gi
  mds:
    requests:
      cpu: 3
      memory: 8Gi
  mgr:
    requests:
      cpu: 1
      memory: 3Gi
  noobaacore:
    requests:
      cpu: 1
      memory: 4Gi
  noobaadb:
    requests:
      cpu: 1
      memory: 4Gi
  osd:
    requests:
      cpu: 2
      memory: 5Gi
    pvc:
      storage: 2Ti

storageClass:
  rgw:
    name: ocs-storagecluster-ceph-rgw
    region: us-east-1  # overwritten
    objectStoreName: ocs-storagecluster-cephobjectstore

  rbd:
    name: ocs-storagecluster-ceph-rbd
    objectStoreName: ocs-storagecluster-cephobjectstore

toolbox:
  name: ocsinit
  enableCephTools: true

global:
  hub:
    region: us-east-1
  xraylab:
    namespace: "openshift-storage"
  datacenter:
    storageClassName: gp2
    region: us-east-1

clusterGroup:
  storageClass: gp2

# Define the odf storageSystem parameters
storageSystem:
  deploy: false
  name: ocs-storagecluster-storagesystem
  namespace: openshift-storage
  spec:
    kind: storagecluster.ocs.openshift.io/v1
    name: ocs-storagecluster
    namespace: ""

# RoleBasedAccessControl
serviceAccountName: odf-node-label-sa
rbac:
  roles:
    - name: label-storage-nodes
      createRole: true
      apiGroups:
        - '""'
      scope:
        cluster: true
      resources:
        - nodes
      verbs:
        - "get"
        - "list"
        - "patch"
        - "update"
    - name: edit-storageclass
      createRole: true
      apiGroups:
        - 'storage.k8s.io'
      scope:
        cluster: true
      resources:
        - storageclasses
      resourceNames:
        - ocs-storagecluster-ceph-rbd
      verbs:
        - "get"
        - "list"
        - "patch"
        - "update"
  roleBindings:
    - name: label-storage-nodes
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: odf-node-label-sa
        namespace: openshift-storage
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: label-storage-nodes
    - name: edit-storageclass
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: odf-node-label-sa
        namespace: openshift-storage
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: edit-storageclass

job:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
