apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  annotations:
    uninstall.ocs.openshift.io/cleanup-policy: delete
    uninstall.ocs.openshift.io/mode: graceful
  finalizers:
  - storagecluster.ocs.openshift.io
  name: ocs-storagecluster
  namespace: {{ .Values.ocs.namespace }}
spec:
  arbiter: {}
  encryption:
    kms: {}
  externalStorage: {}
  managedResources:
    cephBlockPools: {}
    cephCluster: {}
    cephConfig: {}
    cephDashboard: {}
    cephFilesystems: {}
    cephObjectStoreUsers: {}
    cephObjectStores: {}
  mirroring: {}
  multiCloudGateway:
    dbStorageClassName: {{ .Values.cloudProvider.storageClass }}
    reconcileStrategy: standalone
  storageDeviceSets:
  - name: ocs-deviceset
    config: {}
    count: 1
    replica: 3
    resources:
      requests:
        cpu: {{ .Values.ocs.osd.requests.cpu | squote }}
        memory: {{ .Values.ocs.osd.requests.memory }}
    placement: {}
    preparePlacement: {}
    dataPVCTemplate:
      metadata: {}
      spec:
        storageClassName: {{ .Values.global.datacenter.storageClassName }}
        accessModes:
        - ReadWriteOnce
        volumeMode: Block
        resources:
          requests:
            storage: {{ .Values.ocs.osd.pvc.storage }}
      status: {}
    portable: true
