---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: kiosk-extra
  namespace: ansible-automation-platform
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: kiosk-extra
  dataFrom:
  - extract:
      key: {{ .Values.kioskExtra.key }}
