apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: petclinic-build-workspace
spec:
  resources:
    requests:
      storage: 5Gi
  storageClassName: {{ .Values.cloudProvider.storageClass }}-vp
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
